spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update    #For production, this property should be validate
  datasource:
    url: jdbc:postgresql://localhost:5432/product-management
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
