spring:
  profiles: 
    active: git  
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ROHIT-DSCE/shopify.git
          clone-on-start: true
          default-label: main
          force-pull: true
          timeout: 50
