spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/user-management
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver


logging: 
   level:
     com:
       ms: 
         user: DEBUG 
     org:
       springframework: ERROR
       hibernate: ERROR    

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: "http://localhost:5090/eureka"       
